### ISSUE TITLE
idn usernames

### ISSUE THREAD

**Issue by norayr** [dimkr/tootik#38]
do you think you'd like to support unicode usernames?

mastodon and socialhome do not allow to register unicode usernames. but i looked in the activity pub spec and didn't find there a limitation. i think unicode usernames are permitted by the spec.

the other question would be - if mastodon would receive updates from such a user.

**Comment by dimkr** [comment]
> do you think you'd like to support unicode usernames?

Have you tried this? tootik just takes username from CN (in client cert) or asks you for input if username is already taken - AFAIK in both cases it's a UTF-8 string.

**Comment by norayr** [comment]
i tried it long ago, and tried it again now.

if i write something in armenian letters i get: <enteredname> is invalid, enter username.

**Comment by dimkr** [comment]
Currently, tootik doesn't have a `name` property for users, only `preferredUsername`, and it's limited to `a-z0-9`, for compatibility with Mastodon.

This issue will become relevant if and when tootik gains a `name` property, which is supposed to be a human-readable display name or the actual name of a person.

**Comment by norayr** [comment]
still, if you don't want to allow unicode usernames - that's ok, and your decision.

my understanding is that mastodon doesn't allow registrations of unicode usernames. but you have the opportunity to test, if mastodon will allow receiving messages from unicode usernames.

xmpp/jabber implementations allow unicode usernames, also for social media publishing via xmpp (there is such rfc). and they also implement activity pub gateway, so unicode usernames will come to fediverse sooner or later.

**Comment by dimkr** [comment]
I don't think it's a good idea because non-Unicode characters in usernames (as opposed to names) will break the regular expressions used to detect things like mentions. If and when Mastodon allows this - I'll consider doing this in tootik too.
