### ISSUE TITLE
migrations/migration.go:61:20: undefined: migrations

### ISSUE THREAD

**Issue by locrianz** [dimkr/tootik#41]
As of this morning, I can't run `go build ./migrations/`; it gives me this error:

```
migrations/migration.go:61:20: undefined: migrations
```

**Comment by dimkr** [comment]
https://github.com/dimkr/tootik#building

You skipped this step:

```
go generate ./...
```

**Comment by locrianz** [comment]
Seriously, I typed the wrong thing? Oh, fuck me. Sorry.
