### ISSUE TITLE
feed is not getting any posts

### ISSUE THREAD

**Issue by quienn** [dimkr/tootik#87]
I just completed the setup guide, but it looks like there's something wrong.

I can follow other fediverse accounts, that works! I tried accessing the account's mastodon.social followers page and my account and instance is sitting there. But Gemini-side nothing happens, there are no posts.

![image](https://github.com/user-attachments/assets/29bacd5f-1859-4dc1-819c-b47935edff43)

![image](https://github.com/user-attachments/assets/5c489990-f207-40af-8f6c-2ffb07a3385d)

Judging from the `journalctl -u tootik` output, it looks like it's a TLS problem, but I can't see why. (My firewall was set up correctly):

```
oct 24 16:44:50 arcadian tootik[19470]: {"time":"2024-10-24T16:44:50.58371964-06:00","level":"INFO","msg":"Running periodic job","job":"feed"}
oct 24 16:44:50 arcadian tootik[19470]: {"time":"2024-10-24T16:44:50.584706912-06:00","level":"INFO","msg":"Done running periodic job","job":"feed","duration":"928.411µs"}
oct 24 16:54:50 arcadian tootik[19470]: {"time":"2024-10-24T16:54:50.583760705-06:00","level":"INFO","msg":"Running periodic job","job":"feed"}
oct 24 16:54:50 arcadian tootik[19470]: {"time":"2024-10-24T16:54:50.583929105-06:00","level":"INFO","msg":"Running periodic job","job":"poller"}
oct 24 16:54:50 arcadian tootik[19470]: {"time":"2024-10-24T16:54:50.584181503-06:00","level":"INFO","msg":"Done running periodic job","job":"poller","duration":"235.587µs"}
oct 24 16:54:50 arcadian tootik[19470]: {"time":"2024-10-24T16:54:50.585320944-06:00","level":"INFO","msg":"Done running periodic job","job":"feed","duration":"1.488111ms"}
oct 24 17:01:21 arcadian tootik[19470]: {"time":"2024-10-24T17:01:21.604302823-06:00","level":"INFO","msg":"http: TLS handshake error from 206.168.34.223:47760: read tcp 74.208.45.233:443->206.168.34.223:47760: read: connection reset by peer"}
oct 24 17:01:48 arcadian tootik[19470]: {"time":"2024-10-24T17:01:48.397318135-06:00","level":"INFO","msg":"http: TLS handshake error from 206.168.34.223:47654: tls: client offered only unsupported versions: [302 301]"}
oct 24 17:01:50 arcadian tootik[19470]: {"time":"2024-10-24T17:01:50.304343713-06:00","level":"INFO","msg":"http: TLS handshake error from 206.168.34.223:47670: tls: client offered only unsupported versions: [301]"}
oct 24 17:01:52 arcadian tootik[19470]: {"time":"2024-10-24T17:01:52.389654833-06:00","level":"INFO","msg":"http: TLS handshake error from 206.168.34.223:47672: tls: client offered only unsupported versions: []"}
oct 24 17:04:50 arcadian tootik[19470]: {"time":"2024-10-24T17:04:50.583765823-06:00","level":"INFO","msg":"Running periodic job","job":"feed"}
oct 24 17:04:50 arcadian tootik[19470]: {"time":"2024-10-24T17:04:50.584565199-06:00","level":"INFO","msg":"Done running periodic job","job":"feed","duration":"744.371µs"}
oct 24 17:09:11 arcadian tootik[19470]: {"time":"2024-10-24T17:09:11.625663683-06:00","level":"INFO","msg":"http: TLS handshake error from 54.242.85.114:44190: EOF"}
```

**Comment by dimkr** [comment]
1. Check if your instance received any posts (grep logs for "Received a new post") - if you know the users you follow posted anything but don't see anything in logs, try to enable debug logs (`-loglevel -4`) and ensure that `curl -v https://social.072004.xyz` works (no DNS or TLS cert issues)
2. Once your instance received any posts - the feed is updated every 10m, so either wait or restart tootik

**Comment by dimkr** [comment]
I see at least one user is following dimkr@hd.206267.xyz (me) and I can find my posts through search + status page says the server sees >1 federated user and posts. Federation seems to work and I'm closing this issue.

If you can't see old posts by newly followed users, this is normal and expected, at least with the current behavior.

If there's an actual federation bug, please reopen.
