### ISSUE TITLE
the "view profile" feature only seems to be able to find users on mastodon instances.

### ISSUE THREAD

**Issue by not-fiore** [dimkr/tootik#91]
im oh hd.206267.xyz. i tried looking for people i know who i wanted to follow, but it seems like only those that are on mastodon (or glitch-soc, or chuckya, anyways mastodon forks) cannot be found. is federation only 1-way with pleroma/akkoma and *key instances?

**Comment by dimkr** [comment]
Cannot be found in what sense? Have you tried "View profile"?

**Comment by chiccoY2K** [comment]
> Cannot be found in what sense? Have you tried "View profile"?
yes,  that is what ive been doing. might even be because the instances i was looking for were fediblocked, but i have no way of knowing this without access to the instance blocklist.

**Comment by not-fiore** [comment]
yes, that is what ive been doing. might even be that the issue is because the instances ive been looking for are fediblocked, but i have no way to assert that without access to the blocklist. it just seems peculiar that the mastodon profiles ive been trying to look for all work

**Comment by dimkr** [comment]
What do you mean by "work"? Do you reach the profiles you want or reach them but don't see any posts? Each tootik instance only shows posts by users with followers in the instance. You won't be able to see past posts by a user without followers, until they have at least one follower (you or somebody else).

**Comment by not-fiore** [comment]
i wasnt able to reach the profile. however, just tried again with the same ones i tried earlier and it now seems to be fine. closing this
