### ISSUE TITLE
setup & configuration questions

### ISSUE THREAD

**Issue by SmallPatatas** [dimkr/tootik#95]
Attempting to get tootik running alongside a few other services on the same machine.

Similar issues to #44 perhaps?

- running `curl -v https://tootik.patatas.ca` seems to give the expected output.
- I'm running tootik behind nginx, with nginx listening on port 443 and `proxy_pass`ing to port 8080.
- modified the nginx.conf to listen on port 1965 and then send requests to either my existing gemini capsule on internal port 1966, or to tootik on port 8965, using [https://pastebin.com/QHWhAWyM](https://pastebin.com/QHWhAWyM) as a guide.

What works: 
- I can create users via Lagrange 
- I can successfully post DMs to my Mastodon accounts 
- and I can follow those accounts from tootik.

What isn't working yet: 
- cannot see any outside users' posts within Lagrange
- I don't think my Mastodon accounts are actually successfully following my tootik account (?)
- cannot see tootik posts from Mastodon accounts (except DMs).

typical errors I'm getting in logs: 
`"Failed to verify activity","activity":"https://  [mastodon server/account/status]  /activity","type":"Create","error":"failed to verify message: wrong host: 127.0.0.1:8080"}`
Or instead of `Create`, it might be `Follow` or `Accept` or `Delete` activities.

Not sure what else to try. I'm hoping I configured the header forwarding properly in nginx but it's quite possible it's incorrect? Here's my server block:

```
server {
        server_name tootik.patatas.ca;

        include /etc/nginx/default.d/*.conf;

        location / {
                proxy_pass http://127.0.0.1:8080;
#               proxy_pass http://localhost:8080;
                proxy_pass_request_headers on;
                proxy_set_header Signature $http_signature;
                proxy_set_header Collection-Syncronization $http_collection_synchronization;
#               proxy_http_version 1.1; 

        }

        location /inbox/$user {

                proxy_method POST;
                proxy_pass_request_headers on;
                proxy_pass http://127.0.0.1:8080;
#               proxy_pass http://localhost:8080;
#               proxy_http_version 1.1;
                proxy_set_header Signature $http_signature;
                proxy_set_header Collection-Synchronization $http_collection_synchronization;
        }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/tootik.patatas.ca/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/tootik.patatas.ca/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
```
And then lastly here's my tootik.service in case there's anything that jumps out as a possible issue:
```
[Unit]
Description=tootik
After=network.target

[Service]
ExecStart=tootik -plain -domain tootik.patatas.ca -addr 127.0.0.1:8080 -gemaddr :8965 -gopheraddr :70 -fingeraddr :79 -blocklist /home/tootik/tootik-cfg/patatas-blocklist.csv -cert /etc/letsencrypt/live/tootik.patatas.ca/fullchain.pem -key /etc/letsencrypt/live/tootik.patatas.ca/privkey.pem -gemcert /home/tootik/tootik-cfg/gemini-cert.pem -gemkey /home/tootik/tootik-cfg/gemini-key.pem -db /home/tootik/tootik-data/db.sqlite3
User=tootik
Group=tootik
AmbientCapabilities=CAP_NET_BIND_SERVICE
NoNewPrivileges=true
Restart=always

[Install]
WantedBy=multi-user.target
```
Thanks very much! :)

**Comment by SmallPatatas** [comment]
Wheeee!

Got it working :)

For the record: I added a few lines into my server block, which now looks like this:
```
server {
	server_name tootik.patatas.ca;
	
	include /etc/nginx/default.d/*.conf;

	location / {
		proxy_pass http://127.0.0.1:8080;
		proxy_pass_request_headers on;
		proxy_set_header Signature $http_signature;
		proxy_set_header Collection-Syncronization $http_collection_synchronization;
		proxy_http_version 1.1;	
		proxy_set_header Host $host;
		proxy_set_header X-Forwarded-For $remote_addr;
		proxy_set_header X-Forwarded-Proto $scheme;
	}

	location /inbox/$user {
		
		proxy_method POST;
		proxy_pass_request_headers on;
		proxy_pass http://127.0.0.1:8080;
		proxy_http_version 1.1;
		proxy_set_header Signature $http_signature;
		proxy_set_header Collection-Synchronization $http_collection_synchronization;
        	proxy_set_header X-Forwarded-For $remote_addr;
        	proxy_set_header X-Forwarded-Proto $scheme;
        	proxy_set_header Host $host;
	}


    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/tootik.patatas.ca/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/tootik.patatas.ca/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

server {
    if ($host = tootik.patatas.ca) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


	listen 80;
	server_name tootik.patatas.ca;
    return 404; # managed by Certbot


}
```

I'm assuming the two location sections are redundant, so I'll fiddle around with it some more to see - but at present it seems to be federating properly and I don't feel like messing with it any more at the moment ;)

And in case it helps anyone, here's how I modified the instructions at [https://pastebin.com/QHWhAWyM](https://pastebin.com/QHWhAWyM) to direct the `gemini://` traffic:

```
stream {
 
    ###
    ### Setup
    ###
 
    # connection-limiting
    limit_conn_zone               $binary_remote_addr zone=addr:10m;
    limit_conn_log_level          warn;
    limit_conn                    addr 1;
 
    # logging
    log_format                    basic '$remote_addr $upstream_addr [$time_local] '
                                  '$protocol $status $bytes_sent $bytes_received '
                                  '$session_time';
    access_log                    syslog:server=unix:/dev/log basic;
    error_log                     stderr info;
    error_log                     /var/log/nginx/error.log warn;
 
    # map SNI -> backend service
    map $ssl_preread_server_name  $name {
        gemini.patatas.ca	patatas;
	tootik.patatas.ca	tootik;
    }
 
 
    ###
    ### Frontends
    ###
 
    # Gemini
    server {
        listen                    1965;
        ssl_preread               on;
        proxy_buffer_size         16k;
 
        # pass requests directly to the corresponding Gemini server
        proxy_pass                $name;
    }

    ###
    ### Backends
    ###
 
    # personal gemlog
    upstream patatas {
        server                    127.0.0.1:1966;
    }
    # tootik instance
    upstream tootik {
	server			  127.0.0.1:8965;
    }
}
```

**Comment by dimkr** [comment]
Classic case of preserving Host+Signature when proxying, maybe I should make this even clearer in https://github.com/dimkr/tootik/blob/main/SETUP.md#running-behind-a-reverse-proxy

**Comment by SmallPatatas** [comment]
If I actually felt like I knew what I was doing I'd try and write up a PR for you, but I really just kinda flailed around until I stumbled on a working config.

It was a pretty good learning experience - but yeah, if there was an example nginx config in the guide, that would be fantastic too :)

Anyway, great to know that it's possible to run tootik alongside several other things. I'll probably also write a blog post about how to get the setup working; tootik seems like a great way to have decentralized inter-gemini socializing, and most people are probably running a capsule already if they're looking to run tootik.
