### ISSUE TITLE
Additional client certificates

### ISSUE THREAD

**Issue by quienn** [dimkr/tootik#96]
I usually make rotate my client certificate once a year. Most Gemini services these days have some kind of way to add an additional/multiple additional certificates. Looks like tootik doesn't, which is kind of a bum for me.

I guess I could do it by hand somehow, but ideally there should be a way to do it in the UI.

**Comment by dimkr** [comment]
@quienn Please review #97, at least help.gmi. Is this an acceptable solution?

**Comment by quienn** [comment]
hmm, this approach sure is interesting but it works, I like it! Thanks! 🤓
